// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qypdjertxntyhqbpetay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5cGRqZXJ0eG50eWhxYnBldGF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjQ5NDgsImV4cCI6MjA3MDYwMDk0OH0.omVLA2u7nceZZSC-dToJbQ0KejgmeX0n8r2IxJDlYdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});